DataStructuresAssignment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataStructuresAssignment.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

DataStructuresAssignment/Controllers/StackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataStructuresAssignment.Controllers
{
    public class StackController : Controller
    {
        static Stack<string> myStack = new Stack<string>();

        // GET: Stack
        public ActionResult Index()
        {
            ViewBag.MyStack = myStack;

            return View();
        }

        public ActionResult AddOne()
        {
            myStack.Push("New Entry " + (myStack.Count + 1));

            ViewBag.MyStack = myStack;

            return View("Index");
        }
    }
}

DataStructuresAssignment/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>Index</title>
</head>
<body>
    <div class="w3-bar w3-black">
        <a href="@Url.Action("Index", "Stack")" class="w3-bar-item w3-button w3-hover-light-green">Stack</a>
        <a href="@Url.Action("Index", "Queue")" class="w3-bar-item w3-button w3-hover-light-green">Queue</a>
        <a href="@Url.Action("Index", "Dictionary")" class="w3-bar-item w3-button w3-hover-light-green">Dictionary</a>
        <a href="@Url.Action("Index", "Exit")" class="w3-bar-item w3-button w3-hover-light-green">Exit</a>
    </div>
</body>
</html>

DataStructuresAssignment/Views/Stack/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <title>Stack Index</title>
</head>
<body>

    <div class="w3-sidebar w3-black w3-bar-block" style="width:25%">

        <h3 class="w3-bar-item">Stack Menu</h3>
        <a href="@Url.Action("AddOne", "Stack")" class="w3-bar-item w3-button w3-hover-light-green">Add One Item to Stack</a>
        <a href="@Url.Action("HugeList", "Stack")" class="w3-bar-item w3-button w3-hover-light-green">Add Huge List of Items to Stack</a>
        <a href="@Url.Action("Display", "Stack")" class="w3-bar-item w3-button w3-hover-light-green">Display Stack</a>
        <a href="@Url.Action("DeleteOne", "Stack")" class="w3-bar-item w3-button w3-hover-light-green">Delete from Stack</a>
        <a href="@Url.Action("Clear", "Stack")" class="w3-bar-item w3-button w3-hover-light-green">Clear Stack</a>
        <a href="@Url.Action("Search", "Stack")" class="w3-bar-item w3-button w3-hover-light-green">Search Stack</a>
        <a href="@Url.Action("MainMenu", "Stack")" class="w3-bar-item w3-button w3-hover-light-green">Return to Main Menu</a>

    </div>
    @foreach (var sData in ViewBag.MyStack)
    {
        <p>@sData</p>
    }
</body>
</html>